name: Deploy com verificação de segurança

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessário para algumas ferramentas de segurança

        #usa o gitleaks para procurar por 
        #segredos como senhas, tokens e chaves de API no seu código.
      - name: Segurança: Verificação de Segredos
        uses: gitleaks/gitleaks-action@v8 # Use a versão mais recente
        # Opcional: Configure para falhar o build se segredos forem encontrados
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   FAIL_ON_SECRETS: "true"


        #Análise de Vulnerabilidades em Dependências 
        #usa o OWASP Dependency Check para verificar 
        #se há vulnerabilidades conhecidas nas bibliotecas JavaScript e CVEs conhecidas
      - name: Segurança: Análise de Vulnerabilidades em Dependências
        uses: owasp/dependency-check-action@v3 # Use a versão mais recente
        with:
          projectName: 'Mario Run' # Defina um nome para o seu projeto
          format: 'Sarif'
          outputDirectory: 'gl-sarif'


        #Análise de Vulnerabilidades em código JavaScript
        #Uso não sanitizado de innerHTML
        #Manipulação insegura de eventos
        #Uso inseguro de jQuery
        #Incluso PHP
      - name: Segurança: Análise de Segurança (CodeQL)
        uses: github/codeql-action/analyze@v2
        with:
          languages: 'javascript, php'


        #Envia os resultados da análise de vulnerabilidades 
        #para o GitHub Security, onde você pode visualizá-los 
        #na aba "Security" do seu repositório.
      - name: Segurança: Envio de Resultados para o GitHub Security
        uses: github/codeql-action/upload-sarif@v2 # Use a versão mais recente
        with:
          sarif_file: gl-sarif/dependency-check-report.sarif

        #Específicos para análise de vulnerabilidades em PHP
      - name: Segurança: Análise Estática PHP
        uses: docker://phpstan/phpstan
        with:
          args: analyse --level=max --error-format=github

      - name: Segurança: Verificar Vulnerabilidades PHP
        run: |
          curl -sS https://raw.githubusercontent.com/fabpot/local-php-security-checker/master/security-checker.phar -o security-checker.phar
          php security-checker.phar check-local

      - name: Segurança: Análise RIPS para PHP
        uses: docker://rips/rips
        with:
          args: --path=/github/workspace --format=github