name: Deploy com verificação de segurança

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar diretório de relatórios
        run: mkdir -p reports

      # Verificação de segredos
      - name: Segurança - Verificação de Segredos
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sarif-output: 'reports/gitleaks-report.sarif'

      # Análise de dependências
      - name: Segurança - Análise de Dependências (OWASP)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'SQLInjection Test'
          scan-dir: '.'
          format: 'SARIF'
          output: 'reports/'
          fail-on-cvss: 7 # Falha se encontrar vulnerabilidades críticas

      # Análise estática PHP
      - name: Segurança - Análise Estática PHP
        uses: docker://ghcr.io/phpstan/phpstan
        with:
          args: analyse --level=max --error-format=github --error-format=json > reports/phpstan-report.json
        continue-on-error: true

      # Upload de todos os relatórios SARIF
      - name: Segurança - Upload de Relatórios
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            reports/dependency-check-report.sarif
            reports/gitleaks-report.sarif