name: Deploy com verificação de segurança

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Segurança - Verificação de Segredos
        uses: gitleaks/gitleaks-action@v4.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Segurança - Análise de Dependências (OWASP)
        uses: OWASP/dependency-check-action@v3
        with:
          project: 'SQLInjection Test'
          scan-dir: '.'
          format: 'SARIF'
          output: 'dependency-check-report.sarif'

      - name: Upload relatório OWASP
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'dependency-check-report.sarif'
      
      # Upload dos resultados para GitHub Security
      - name: Segurança - Envio de Resultados para o GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: './dependency-check-reports/dependency-check-report.sarif'

      # Análise estática PHP
      - name: Segurança - Análise Estática PHP
        uses: docker://phpstan/phpstan
        with:
          args: analyse --level=max --error-format=github ./src